#!/bin/bash

URL="https://pokeapi.co/api/v2/pokemon/"
DATA_FILE="data.json"
ERROR_FILE="errors.txt"
error_handler() {
    echo "$1" >> "$ERROR_FILE"
    exit 1
}
trap 'echo "An error occurred. Exiting..."; exit 1' ERR

curl -s "$URL" -o "temp.txt" || error_handler "Curl Failed to do its thing"

grep -o '"name":"pikachu","url":"[^"]*"' "temp.txt" > "$DATA_FILE"
cat "$DATA_FILE"
rm temp.txt
