#!/bin/bash

JSON_FILE="data.json"

URL=$(awk -F'"' '{ print $8 }' "$JSON_FILE")

CHARACTER=$(curl -s $URL)

name="$(echo "$CHARACTER" | jq -r '.name')"
type="$(echo "$CHARACTER" | jq -r '.type')"
formatted_weight="$(echo "$CHARACTER" | jq -r '.weight')"
formatted_height="$(echo "$CHARACTER" | jq -r '.height')"

sed 's/name/name/g' data.json

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
